### PR TITLE
Symfony 6 Composer update

### PR DESCRIPTION
**Pull request by guilhermegarcz**
Added Symfony 6 to composer.json

### CODE REVIEW

**Comment by khaperets** [comment]
Conflicts need to be resolved

**Comment by mehdibo** [comment]
Hello @guilhermegarcz!

Do you still have time to resolve the conflicts? if not I can submit a PR

**Comment by guilhermegarcz** [comment]
> Do you still have time to resolve the conflicts? if not I can submit a PR

Yea that would be nice

**Comment by mehdibo** [comment]
#10

**Comment by khaperets** [comment]
Resolved in PR #10

**Pull request closed without merging**
