### PR TITLE
rename getContentType() method on Request class to getContentTypeFormat()

### LINKED ISSUE #18: getContentType method is deprecated as of Symfony 6.2
```
User Deprecated: Since symfony/http-foundation 6.2: The \"Symfony\\Component\\HttpFoundation\\Request::getContentType()\" method is deprecated, use \"getContentTypeFormat()\" instead.
```

### PR DESCRIPTION
**Pull request by dannyvankooten**
Fixes php-bundles/json-request-bundle#18

### CODE REVIEW

**Comment by frandzdy** [comment]
Can you merge this MR ?

**Comment by frandzdy** [comment]
Did you update the require section in the composer.yaml ?

`
"require": {
        "php": ">=7.4 || ^8.0",
        "ext-json": "*",
        "symfony/framework-bundle": "^4.3 || ^5.0 || ^6.0 || ^7.0"
    },
`

**Comment by MikaBeDev** [comment]
@dannyvankooten is there any plans to merge this soon ?

**Comment by dannyvankooten** [comment]
I’m not the one with the capabilities to merge, unfortunately.

**Pull request merged**
